require 'personal/plugins'
require 'personal/options'
require 'personal/groups'
require 'personal/keymaps'
require 'personal/window-keymaps'
require 'personal/globals'
require 'personal/coc-config'

require 'dap/debugging'
-- require 'lsp'
-- require 'lsp/completion'
-- require 'lsp/null_ls'
require 'personal/miscellaneous'
require 'personal/telescope-config'
require 'personal/treesitter'
