column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle" # [AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle]
call_parentheses = "None" # [Always, NoSingleString, NoSingleTable, None]

